# Change these first
owner: pichien # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: 官方網站
    url: https://www.wic.tw
  - name: 熱處理及工業物聯網技術專區
    url: http://wic.sytes.net/iiot.html    
  - name: 技術部落格
    url: https://wic.tw/blog

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** 是開放原始碼的運轉監視及狀態頁面，在 GitHub 上運作"
  introMessage: 滙智實業網站的運轉監視
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "* */4 * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
